language: node_js

node_js:
  - "8.16"

before_deploy:
  - npm run build
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 4a2208e59709b8608cdbd41755199c42b218d5e2
  keep-history: true
  on:
    branch: master
    node: "8.16"
